#
name: Automatic doc checks

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:

  workflow_dispatch:
    # Manual trigger


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: "docs"
      fetch-depth: 0
