name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.1.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}" # FIXME: current token will expire in 2023-07-04
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  integration-test-password-rotation-lxd:
    name: Integration tests for password-rotation (lxd)
    needs:
      - lib-check
      - lint
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          bootstrap-options: "--agent-version 2.9.29"
      - name: Run integration tests
        run: tox -e integration-password-rotation

  integration-test-provider-lxd:
    name: Integration tests for provider (lxd)
    needs:
      - lib-check
      - lint
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          bootstrap-options: "--agent-version 2.9.29"
      - name: Run integration tests
        run: tox -e integration-provider

  integration-test-scaling-lxd:
    name: Integration tests for scaling (lxd)
    needs:
      - lib-check
      - lint
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          bootstrap-options: "--agent-version 2.9.29"
      - name: Run integration tests
        run: tox -e integration-scaling

  integration-test-tls-lxd:
    name: Integration tests for tls (lxd)
    needs:
      - lib-check
      - lint
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          bootstrap-options: "--agent-version 2.9.29"
      - name: Run integration tests
        run: tox -e integration-tls

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - lib-check
      - lint
      - unit-test
      - integration-test-password-rotation-lxd
      - integration-test-provider-lxd
      - integration-test-scaling-lxd
      - integration-test-tls-lxd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.1.0-rc
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.1.0-rc
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
